export const ACTIONS = {
  SET_OPPONENT: 'SET_OPPONENT',
  SET_IS_CONNECTED: 'SET_IS_CONNECTED',
  SET_USER_USERNAME: 'SET_USER_USERNAME',
  SET_USER_ID: 'SET_USER_ID',
  // SET_SOCKET_AUTH: 'SET_SOCKET_AUTH',
  // SET_CONNECTED_SOCKET: 'SET_CONNECTED_SOCKET',
  SET_GAME_STATUS: 'SET_GAME_STATUS',
  SET_USERS: 'SET_USERS',
  SET_PLAYERS: 'SET_PLAYERS',
  UPDATE_GAME_GRID: 'UPDATE_GAME_GRID',
  SET_NEXT_TURN: 'SET_NEXT_TURN',
  SET_WINNER: 'SET_WINNER',
  RESTART_GAME: 'RESTART_GAME',
  USER_LEFT_GAME: 'USER_LEFT_GAME'
}